# Generated by Django 2.2.2 on 2019-06-28 16:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=20)),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('country', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('publisher', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
